pipeline {
  environment {
    registry = "swaninho/express-authors-api"
    registryCredential = 'docker-hub-credentials'
    dockerImage = ''
  }
  agent any
  tools {nodejs "NodeJs"}
  stages {
    stage('Install dependencies of the app') {
      steps {
        dir('express-authors-api') {
          discordSend description: 'Jenkins Pipeline STARTED', footer: "footer desc with vars: ${env.JOB_BASE_NAME}` (build #${BUILD_NUMBER})", image: '', link: env.BUILD_URL, result: currentBuild.currentResult, scmWebUrl: '', thumbnail: '', title: JOB_NAME, webhookURL: 'https://discord.com/api/webhooks/1075315756947996702/qEWoL4WcROyFrfXo1_moxnMzaQBfDrHPSCg-OcOoQLTx9iu0w4UE369aF8vSJ5-q6EvT'
          sh 'npm install'
        }
      }
    }
    stage('Run unit tests') {
      steps {
        dir('express-authors-api') {
          sh 'npm run test -- authors.test.js'
        }
      }
    }
    stage('Building Docker image') {
      steps{
        dir('express-authors-api') {
          script {
            dockerImage = docker.build(registry + ":$BUILD_NUMBER")
          } 
        }
      }
    }
    stage('Deploy Docker image') {
      steps{
        dir('express-authors-api') {
          script {
            docker.withRegistry( '', registryCredential ) {
              dockerImage.push()
            }
          }
        }
      }
    }
    stage('Deploy to PREPROD env') {
      steps{
        dir('express-authors-api') {
          sh 'docker ps -f name=^preprod$ -q | xargs --no-run-if-empty docker container stop'
          sh 'docker container ls -a -fname=^preprod$ -q | xargs -r docker container rm'
          script{
            dockerImage.run('--restart always --name preprod -p 8082:8082')
            dockerImage.inside{
                sh 'npm run test -- performance.test.js'
            }
          }   
        }
      }
    }

    stage('Deploy to ACCEPTANCE env') {
      steps{
        dir('express-authors-api') {
          sh 'docker ps -f name=^acceptance$ -q | xargs --no-run-if-empty docker container stop'
          sh 'docker container ls -a -fname=^acceptance$ -q | xargs -r docker container rm'
          script{
            dockerImage.run('--restart always --name acceptance -p 8083:8083')
            dockerImage.inside{
                sh 'npm run test -- authors.test.js'
            }
          }   
        }
      }
    }

    stage('Deploy to PROD env') {
      steps{
        dir('express-authors-api') {
          sh 'docker ps -f name=^prod$ -q | xargs --no-run-if-empty docker container stop'
          sh 'docker container ls -a -fname=^prod$ -q | xargs -r docker container rm'
          script{
            dockerImage.run('--restart always --name prod -p 8084:8084')
          }   
        }
      }
    }
    
  }
  post {
    always {
      echo 'Send discord notification of build status'
      discordSend description: 'Jenkins Pipeline FINISHED : ' + currentBuild.currentResult, footer: "footer desc with vars: ${env.JOB_BASE_NAME}` (build #${BUILD_NUMBER})", image: '', link: env.BUILD_URL, result: currentBuild.currentResult, scmWebUrl: '', thumbnail: '', title: JOB_NAME, webhookURL: 'https://discord.com/api/webhooks/1075315756947996702/qEWoL4WcROyFrfXo1_moxnMzaQBfDrHPSCg-OcOoQLTx9iu0w4UE369aF8vSJ5-q6EvT', successful: currentBuild.resultIsBetterOrEqualTo('SUCCESS')
    }
  }
}
