pipeline {
  environment {
    registry = "http://localhost:8082/repository/docker-hosted/"
    registryCredential = 'docker-nexus'
    dockerImage = ''
  }
  agent any
  tools {nodejs "NodeJs"}
  stages {
    stage('Install dependencies of the app') {
      steps {
        dir('express-authors-api') {
          sh 'npm install'
        }
      }
    }
    stage('Test the app') {
      steps {
        dir('express-authors-api') {
          sh 'npm run test'
        }
      }
    }
    stage('Building Docker image') {
      steps{
        dir('express-authors-api') {
          script {
            dockerImage = docker.build(registry + ":$BUILD_NUMBER")
          }
        }
      }
    }
    stage('Deploy Docker image') {
      steps{
        dir('express-authors-api') {
          script {
            docker.withRegistry( '', registryCredential ) {
              dockerImage.push('oui')
            }
          }
        }
      }
    }
  }
}