pipeline {
  environment {
    registry = "http://192.168.1.82:8082/"
    registryCredential = 'docker-nexus'
    dockerImage = ''
    imageName = "express-authors-api"
  }
  agent any
  tools {nodejs "NodeJs"}
  stages {
    stage('Install dependencies of the app') {
      steps {
        dir('express-authors-api') {
          sh 'npm install'
        }
      }
    }
    stage('Test the app') {
      steps {
        dir('express-authors-api') {
          sh 'npm run test'
        }
      }
    }
    stage('Building Docker image') {
      steps{
        dir('express-authors-api') {
          script {
            dockerImage = docker.build(imageName)
          }
        }
      }
    }
    stage('Deploy Docker image') {
      steps{
        dir('express-authors-api') {
          script {
            docker.withRegistry(registry, registryCredential){
              dockerImage.push('latest')
            }
          }
        }
      }
    }
  }
}